site_name: "xpuz"
site_description: "Play procedurally generated crosswords."
site_url: "https://xpuz.readthedocs.io/"
repo_url: "https://github.com/tomasvana10/xpuz/"
edit_uri: "edit/main/docs/"
repo_name: "xpuz"
copyright: Copyright &copy; 2023-2024 Tomas Vana

watch:
  - src
  
nav:
  - Home: 
    - index.md
    - Contributing: contributing.md
    - License: license.md
    - Credits: credits.md
    - Gallery: gallery.md
  - Getting Started:
    - installation.md
  - User Guide: user_guide.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Code Reference: reference/ # defer to gen-files + literate-nav


theme:
  name: material
  font: 
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-page-variant
    annotation: material/plus-circle
  favicon: favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        name: Switch to light mode
        icon: material/brightness-auto
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        name: Switch to dark mode
        icon: material/brightness-7
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        name: Switch to system preference
        icon: material/brightness-4
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.select
    - content.code.annotate
    - content.code.annotations
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow

markdown_extensions:
  - callouts
  - footnotes
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - mkdocs-click
  - pymdownx.snippets
  - md_in_html
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - def_list
  - admonition
  - tables
  - toc:
      permalink: "¤"

plugins:
  - search
  - markdown-exec
  - gen-files:
      scripts:
      - docs/scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          paths: [src]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            show:
              private: true
            filters: []
            heading_level: 1
            inherited_members: false  # very important to have this off
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
